version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "news"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-u3wpq72dikbw"
s3_prefix = "news"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
